language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install

script: phpunit --bootstrap vendor/autoload.php tests/*Test.php